# Generated by Django 4.2.5 on 2023-09-26 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('site', models.CharField(max_length=40)),
                ('insta', models.CharField(max_length=30)),
                ('face', models.CharField(max_length=30)),
                ('twitter', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Continente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Diretor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('site', models.CharField(max_length=40)),
                ('insta', models.CharField(max_length=30)),
                ('face', models.CharField(max_length=30)),
                ('twitter', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Episodio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('duracao', models.DurationField()),
                ('data_disponibilizacao', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('duracao', models.DurationField()),
                ('sinopse', models.CharField(max_length=400)),
                ('site_oficial', models.CharField(max_length=40)),
                ('data_lancamento', models.DateField()),
                ('nota_avaliacao', models.DecimalField(decimal_places=2, max_digits=8)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.categoria')),
                ('diretor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.diretor')),
            ],
        ),
        migrations.CreateModel(
            name='Nacionalidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('continente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.continente')),
                ('nacionalidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.nacionalidade')),
            ],
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('duracao', models.DurationField()),
                ('sinopse', models.CharField(max_length=400)),
                ('site_oficial', models.CharField(max_length=40)),
                ('data_lancamento', models.DateField()),
                ('nota_avaliacao', models.DecimalField(decimal_places=2, max_digits=8)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.categoria')),
                ('diretor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.diretor')),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pais')),
            ],
        ),
        migrations.CreateModel(
            name='Temporada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('QtdEpisodios', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SerieEpisodio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episodio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.episodio')),
                ('serie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.serie')),
                ('temporada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.temporada')),
            ],
        ),
        migrations.CreateModel(
            name='FilmeAtor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ator')),
                ('filme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.filme')),
            ],
        ),
        migrations.AddField(
            model_name='filme',
            name='pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pais'),
        ),
        migrations.AddField(
            model_name='diretor',
            name='nacionalidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.nacionalidade'),
        ),
        migrations.AddField(
            model_name='ator',
            name='nacionalidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.nacionalidade'),
        ),
    ]
