# Generated by Django 4.2.5 on 2023-10-02 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pais',
            name='nacionalidade',
        ),
        migrations.AlterField(
            model_name='ator',
            name='face',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='ator',
            name='insta',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='ator',
            name='twitter',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nome',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='diretor',
            name='face',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='diretor',
            name='insta',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='diretor',
            name='twitter',
            field=models.CharField(max_length=40),
        ),
        migrations.RemoveField(
            model_name='filme',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='filmeator',
            name='ator',
        ),
        migrations.AlterField(
            model_name='nacionalidade',
            name='nome',
            field=models.CharField(max_length=40),
        ),
        migrations.RemoveField(
            model_name='serie',
            name='categoria',
        ),
        migrations.AddField(
            model_name='filme',
            name='categoria',
            field=models.ManyToManyField(to='app.categoria'),
        ),
        migrations.AddField(
            model_name='filmeator',
            name='ator',
            field=models.ManyToManyField(to='app.ator'),
        ),
        migrations.AddField(
            model_name='serie',
            name='categoria',
            field=models.ManyToManyField(to='app.categoria'),
        ),
    ]
