# Generated by Django 4.2.5 on 2023-10-02 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_pais_nacionalidade_alter_ator_face_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ator',
            name='face',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='ator',
            name='insta',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='ator',
            name='site',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ator',
            name='twitter',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='diretor',
            name='face',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='diretor',
            name='insta',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='diretor',
            name='site',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='diretor',
            name='twitter',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='filme',
            name='site_oficial',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='serie',
            name='site_oficial',
            field=models.CharField(max_length=100),
        ),
    ]
